### ISSUE TITLE
Export StoredProcess code

### ISSUE THREAD

**Issue by ur-mayara** [cjdinger/sas-eg-automation#2]
Can you add a Case to export the sas code if the item is an egStoredProcess?

I'm trying to do like the egCode but give me an error (438) and I didn't find the attributes/Method documentation to understand it.

Thank you very much!

**Comment by cjdinger** [comment]
Sorry, the StoredProcess class doesn't support a Code property.  It supports just Log and Results.

**Comment by ur-mayara** [comment]
Thank you Chris.

Maybe you can help me to solve this particular problem. 
I need to export automatically, as a sas code, all elements of a process flow. 
I tried the Stored Proces because has a menu option to export on EG Client that will be easy for the users to generate this element each time that some modification was done.

Do you know another way to export as sas code the process flow from an egp?

Any idea helps me.
Thank you again.

**Comment by cjdinger** [comment]
Does [the ExtractCode example help](https://github.com/cjdinger/sas-eg-automation/blob/master/vbscript/ExtractCode.vbs)? That pulls all SAS code out of each process flow and collects it into a folder.

**Comment by ur-mayara** [comment]
Thank you Chris.

I found a way inspired on your code.
