### ISSUE TITLE
Dynamically change imported file

### ISSUE THREAD

**Issue by shirubei** [cjdinger/sas-eg-automation#3]
Got stuck in dynamically changing file which imported in "data import" task from python using SAS EG COM for several days.
Please help.
I've tried the FileName property of Item class when the type is 23(egFile) but it's readonly.
Any suggestions ?
Appreciated your awesome work and thank you.

**Comment by cjdinger** [comment]
Hi, thanks for the comment. Yes, the automation model does not allow you to change the filename property. For a task like this, I'd recommend converting the Import Task to a code step and use PROC IMPORT or DATA step to read the file. If it's a local file and SAS is remote, then use the Copy Files task to move it where SAS can read it. Copy Files allows you to use macro variables to set source and destination names.

**Comment by shirubei** [comment]
Thank you Chris for the rapid response.
Then I'll covert it to a code step.

**Comment by shirubei** [comment]
Close since alternative method provided by Chris.
Thank you again.
